---
Name: "OrdererOrg"
ID: "OrdererMSP"
MSPDir: "crypto-config/ordererOrganizations/example.com/msp"
Policies:
  Readers:
    Type: "Signature"
    Rule: "OR('OrgName.member')"
  Writers:
    Type: "Signature"
    Rule: "OR('OrgName.member')"
  Admins:
    Type: "Signature"
    Rule: "OR(OrgName.admin)"
