---
OrdererOrgs:
- Name: "Orderer"
  Domain: "example.com"
  EnableNodeOUs: true
  Specs:
  - Hostname: "orderer"
PeerOrgs:
- Name: "Org0"
  Domain: "org0.example.com"
  EnableNodeOUs: true
  Template:
    Count: 2
- Name: "Org1"
  Domain: "org1.example.com"
  EnableNodeOUs: true
  Template:
    Count: 2
